### ISSUE TITLE
function not defined

### ISSUE THREAD

**Issue by ashish-ch-98** [martijnversluis/ChordJS#74]
when I use a function as defined in the documentation TypeError occurs. For example if I use Chord.parse('G/C'), an error message is shown "TypeError: Chord.parse is not a function".

**Comment by martijnversluis** [comment]
Hi @ashish-ch-98 Could you share the complete code, including the part where you load `chordjs`? Are you using `require()` or `import`?

**Comment by ashish-ch-98** [comment]
`var Chord = require('chordjs');

var chord = Chord.parse('G/C');
console.log(chord.toString());`

I also tried it on runkit, it was also showing the same error.

**Comment by martijnversluis** [comment]
Seems like the `require` syntax is indeed not working.

You can fix it by appending `.default` to `require(...)`:

```
var Chord = require('chordjs').default;
var chord = Chord.parse('G/C');
console.log(chord.toString());
```

**Comment by ashish-ch-98** [comment]
Thanks, it worked.

**Comment by martijnversluis** [comment]
Nice! Thanks for letting me know, I just updated the readme 👍
