### ISSUE TITLE
example of transposing every chord in ChordSheet

### ISSUE THREAD

**Issue by paulrobertpine** [martijnversluis/ChordJS#76]
Hi there and thanks for your work here. 

I'm wondering if you could share a simple example of transposing every Chord in a ChordSheet? 

Thanks

**Comment by martijnversluis** [comment]
Hi @paulrobertpine. Thanks for your question. 

Transposing an entire chord sheet will require both ChordJS and ChordSheetJS. You can find a code sample in the project that combines the two, ChordFiddle. This is a file containing all transformations that can be performed from the ChordFiddle UI: https://github.com/martijnversluis/ChordFiddle/blob/master/src/utils/chord_sheet_transformations.js#L36.

Please let me know if this sample is helpful .

**Comment by paulrobertpine** [comment]
thanks, I figured it out. The file you sent helped. Here's what I ended up
with:

https://github.com/paulrobertpine/gatsby-songbook/blob/master/src/templates/song.jsx


and you can see it working here:

https://songbook.netlify.app/

Thanks,
Paul

**Comment by martijnversluis** [comment]
Nice job, that works nice! Are you writing the chords sheets yourself or do you import them from somewhere?

**Comment by paulrobertpine** [comment]
I do a mix. Often what I do is copy and paste from Ultimate Guitar of whatnot into your ChordFiddle app and then paste into a markdown file, one for each song. See:

https://github.com/paulrobertpine/gatsby-songbook/tree/master/songs
